export const SOURCE_LABELS = {
  price: 'Precio',
  plugInHybrid: 'Híbrido enchufable',
  kmpl: 'Rendimiento km/L',
  kmPerKwh: 'Rendimiento km/kWh',
  batteryCapacityKwh: 'Batería',
  chargerPowerKw: 'Potencia cargador',
  uberKmPerTrip: 'Km por viaje',
  monthlyInsurance: 'Seguro (póliza Uber)',
  annualMaintenance: 'Mantenimiento base',
  monthlyRefrendo: 'Refrendo/Tenencia',
  dataPlan: 'Datos móviles',
  carWash: 'Lavado',
  carWashTips: 'Propinas',
  miscellaneous: 'Misceláneos',
  accessories: 'Accesorios',
  uberWearFactor: 'Desgaste Uber',
  depreciationRate: 'Depreciación',
  salesFactor: 'Factor de venta',
  toxicologyReport: 'Examen toxicológico',
  uberCertification: 'Certificación Uber',
  condition: 'Condición (nuevo/usado)',
  odometerKm: 'Kilometraje',
  repairReserveAnnual: 'Reserva de reparaciones',
  depreciationMethod: 'Método de depreciación',
  firstYearDepreciation: 'Caída 1er año',
  sellingCostPct: 'Costo de venta',
  interestRate: 'Tasa de crédito',
  acquisitionFees: 'Gastos de adquisición',
  // Régimen fiscal, financiamiento, seguro y riesgo
  insuranceMode: 'Modo de seguro',
  insurancePctOfValue: 'Seguro (% del valor)',
  taxRegime: 'Régimen fiscal Uber',
  resicoRate: 'Retención RESICO',
  financeType: 'Tipo de financiamiento',
  balloonPct: 'Valor residual (globo)',
  leaseMonthly: 'Renta de arrendamiento',
  leaseDownPayment: 'Pago inicial arrendamiento',
  // NUEVOS: depreciación de usados, garantía, carga pública, pérdida total
  usedDepreciationRate: 'Depreciación de usados',
  warrantyYearsRemaining: 'Garantía restante',
  publicChargeFraction: 'Fracción de carga pública',
  publicChargePrice: 'Precio de carga pública',
  theftLossProbAnnual: 'Riesgo de pérdida total',
  theftDeductiblePct: 'Deducible cobertura amplia',
};
